services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  back_end:
    build: ./backend

    depends_on:
      postgres:
        condition: service_healthy

  front-end:
    build:
      context: ./front-end

    container_name: vue_front-end

    restart: always

    ports:
      - "80:80"

    depends_on:
      - back_end

volumes:
  postgres_data: