services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres_userhub
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: fastapi-python312-slim:dev

    build:
      context: ./back_end

    volumes:
      - ./back_end:/app

    restart: always

    ports:
      - "5000:5000"
      - "5678:5678"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DEBUG: ${DEBUG}

  frontend:
    image: vue-node22:dev

    build:
      context: ./front_end

    volumes:
      - ./front_end:/app

    restart: always

    ports:
      - "8080:80"

    depends_on:
      - backend

volumes:
  postgres_data: